name: DeluxeBazaar
main: me.sedattr.deluxebazaar.DeluxeBazaar

author: SedatTR
version: 11.2
api-version: 1.13
folia-supported: true

description: The best, cheap, advanced, fully customizable bazaar plugin; like popular server!
website: https://discord.gg/nchk86TKMT
softdepend:
  - Vault
  - CoinsEngine
  - HeadDatabase
  - ProtocolLib
  - RoyaleEconomy
  - PlaceholderAPI
  - PlayerPoints
  - Lands
  - EcoBits
  - ExecutableItems
  - MMOItems
  - EcoItems
  - libreforge
  - eco
  - DeluxeBazaarRedis
  - CMI

commands:
  bazaar:
    description: Default bazaar command.
    aliases: [deluxebazaar, bz, bzr]
  bazaaradmin:
    description: Default bazaar admin command.
    aliases: [deluxebazaaradmin, bzadmin, bzradmin]

permissions:
  deluxebazaar.order.buy.*:
    description: Unlimited maximum active buy orders.
    default: op
  deluxebazaar.order.sell.*:
    description: Unlimited maximum active sell offers.
    default: op
  deluxebazaar.order.buy.7:
    description: Allows up to 7 active buy orders (highest buy.<n> wins).
    default: false
  deluxebazaar.order.sell.7:
    description: Allows up to 7 active sell offers (highest sell.<n> wins).
    default: false